# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200103_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.file_modi),
        ),
    ]
